Repository input-output-hk/react-polymorph, pull requests merged in 2018-11, with the labels that each got.

#89 [DDW-446] Add display name to components
  CHANGELOG.md
  source/components/Autocomplete.js
  source/components/Bubble.js
  source/components/Button.js
  source/components/Checkbox.js
  source/components/FormField.js
  source/components/HOC/GlobalListeners.js
  source/components/HOC/withTheme.js
  source/components/Input.js
  source/components/LoadingSpinner.js
  source/components/Modal.js
  source/components/NumericInput.js
  source/components/Options.js
  source/components/ProgressBar.js
  source/components/Radio.js
  source/components/Select.js
  source/components/TextArea.js
  source/components/ThemeProvider.js
  source/components/Tooltip.js
  source/components/layout/Flex.js
  source/components/layout/FlexItem.js
  source/utils/props.js
Labels: feature

#91 [DDW-375] Adjust NumericInput maxAfterDot Config
  CHANGELOG.md
  __tests__/NumericInput.behavior.test.js
  source/components/NumericInput.js
  stories/NumericInput.stories.js
Labels: bug

#93 [DDW-371] fix flow typing for components
  .eslintrc
  CHANGELOG.md
  __tests__/Autocomplete.behavior.test.js
  __tests__/NumericInput.behavior.test.js
  __tests__/__snapshots__/Button.test.js.snap
  __tests__/__snapshots__/Checkbox.test.js.snap
  __tests__/__snapshots__/NumericInput.test.js.snap
  __tests__/__snapshots__/Radio.test.js.snap
  __tests__/__snapshots__/Switch.test.js.snap
  __tests__/__snapshots__/Toggler.test.js.snap
  package.json
  source/components/Autocomplete.js
  source/components/Bubble.js
  source/components/Button.js
  source/components/Checkbox.js
  source/components/FormField.js
  source/components/HOC/withTheme.js
  source/components/Header.js
  source/components/InfiniteScroll.js
  source/components/Input.js
  source/components/LoadingSpinner.js
  source/components/Modal.js
  source/components/NumericInput.js
  source/components/Options.js
  source/components/ProgressBar.js
  source/components/Radio.js
  source/components/Select.js
  source/components/TextArea.js
  source/components/ThemeProvider.js
  source/components/Tooltip.js
  source/components/layout/Base.js
  source/components/layout/Flex.js
  source/components/layout/FlexItem.js
  source/components/layout/Grid.js
  source/components/layout/GridItem.js
  source/components/layout/Gutter.js
  source/skins/simple/BubbleSkin.js
  source/skins/simple/HeaderSkin.js
  source/skins/simple/InputSkin.js
  source/skins/simple/ModalSkin.js
  source/skins/simple/TextAreaSkin.js
  source/skins/simple/TooltipSkin.js
  source/utils/layout.js
  source/utils/props.js
  source/utils/themes.js
  yarn.lock
Labels: chore

#92 [DDW-376] Rename CSS Variables and Expand Theme Configuration
  CHANGELOG.md
  source/themes/simple/SimpleAutocomplete.scss
  source/themes/simple/SimpleBubble.scss
  source/themes/simple/SimpleButton.scss
  source/themes/simple/SimpleCheckbox.scss
  source/themes/simple/SimpleFormField.scss
  source/themes/simple/SimpleGutter.scss
  source/themes/simple/SimpleHeader.scss
  source/themes/simple/SimpleInfiniteScroll.scss
  source/themes/simple/SimpleInput.scss
  source/themes/simple/SimpleLoadingSpinner.scss
  source/themes/simple/SimpleModal.scss
  source/themes/simple/SimpleOptions.scss
  source/themes/simple/SimpleProgressBar.scss
  source/themes/simple/SimpleRadio.scss
  source/themes/simple/SimpleSelect.scss
  source/themes/simple/SimpleSwitch.scss
  source/themes/simple/SimpleTextArea.scss
  source/themes/simple/SimpleToggler.scss
  source/themes/simple/SimpleTooltip.scss
  source/themes/simple/_theme.scss
  source/themes/simple/mixins/arrow.scss
  stories/theme-customizations/Autocomplete.custom.scss
  stories/theme-customizations/Bubble.custom.scss
  stories/theme-customizations/Button.custom.scss
  stories/theme-customizations/Checkbox.custom.scss
  stories/theme-customizations/Input.custom.scss
  stories/theme-customizations/Modal.custom.scss
  stories/theme-customizations/Options.custom.scss
  stories/theme-customizations/Radio.custom.scss
  stories/theme-customizations/Select.custom.scss
  stories/theme-customizations/Switch.custom.scss
  stories/theme-customizations/TextArea.custom.scss
  stories/theme-customizations/Toggler.custom.scss
  stories/theme-customizations/Tooltip.custom.scss
  stories/theme-overrides/customProgressBar.scss
Labels: chore

#94 [DDW-488] Fix NumericInput Carrot Malfunction
  CHANGELOG.md
  source/components/NumericInput.js
Labels: bug
