Repository input-output-hk/react-polymorph, pull requests merged in 2018-07, with the labels that each got.

#68 [DDW-337] fix select arrow styling to allow color overrides
  CHANGELOG.md
  package.json
  source/components/Bubble.js
  source/components/Input.js
  source/components/Options.js
  source/components/Select.js
  source/skins/simple/OptionsSkin.js
  source/skins/simple/SelectSkin.js
  source/themes/simple/SimpleSelect.scss
  source/themes/simple/assets/select-arrow.svg
  source/themes/simple/assets/select-down-arrow-focus.svg
  source/themes/simple/assets/select-down-arrow.svg
  source/themes/simple/assets/select-open-arrow.svg
  source/themes/simple/assets/select-up-arrow-focus.svg
  source/themes/simple/assets/select-up-arrow.svg
  stories/theme-customizations/Select.custom.scss
  stories/theme-customizations/assets/select-arrow.svg
  stories/theme-customizations/assets/select-down-arrow.svg
  stories/theme-customizations/assets/select-open-arrow.svg
  stories/theme-customizations/assets/select-up-arrow.svg
  yarn.lock
Labels: bug

#73 [DDW-352] show red error state border also around focused textareas
  CHANGELOG.md
  source/themes/simple/SimpleTextArea.scss
Labels: bug

#77 Improve theme exports
  CHANGELOG.md
  source/components/HOC/ThemeContext.js
  source/components/ThemeProvider.js
  source/themes/API/autocomplete.js
  source/themes/API/bubble.js
  source/themes/API/button.js
  source/themes/API/checkbox.js
  source/themes/API/formfield.js
  source/themes/API/index.js
  source/themes/API/input.js
  source/themes/API/modal.js
  source/themes/API/options.js
  source/themes/API/radio.js
  source/themes/API/select.js
  source/themes/API/switch.js
  source/themes/API/textarea.js
  source/themes/API/toggler.js
  source/themes/API/tooltip.js
  source/themes/simple/index.js
  stories/Select.stories.js
  stories/ThemeProvider.stories.js
  stories/Tooltip.stories.js
Labels: chore

#74 Chore/ddw 245 integrate new render props architecture with daedalus
  CHANGELOG.md
  source/components/HOC/ThemeContext.js
  source/themes/simple/SimpleCheckbox.scss
  source/themes/simple/SimpleInput.scss
  source/themes/simple/SimpleTextArea.scss
  stories/Autocomplete.stories.js
  stories/Bubble.stories.js
  stories/Button.stories.js
  stories/Checkbox.stories.js
  stories/Input.stories.js
  stories/Modal.stories.js
  stories/NumericInput.stories.js
  stories/Options.stories.js
  stories/Radio.stories.js
  stories/Select.stories.js
  stories/Switch.stories.js
  stories/TextArea.stories.js
  stories/Toggler.stories.js
  stories/Tooltip.stories.js
  stories/helpers/theming.js
Labels: WIP, chore

#81 [DDW-367] use empty theme as default to avoid duplicated styles
  __tests__/Autocomplete.behavior.test.js
  __tests__/Autocomplete.test.js
  __tests__/Bubble.test.js
  __tests__/Button.test.js
  __tests__/Checkbox.test.js
  __tests__/FormField.test.js
  __tests__/Input.test.js
  __tests__/NumericInput.behavior.test.js
  __tests__/NumericInput.test.js
  __tests__/Options.test.js
  __tests__/Radio.test.js
  __tests__/Select.test.js
  __tests__/Switch.test.js
  __tests__/TextArea.test.js
  __tests__/Toggler.test.js
  __tests__/helpers/theming.js
  source/components/HOC/ThemeContext.js
Labels: bug

#75 [DDW-27] react polymorph loading spinner
  CHANGELOG.md
  package.json
  source/components/Autocomplete.js
  source/components/LoadingSpinner.js
  source/components/Options.js
  source/skins/simple/LoadingSpinnerSkin.js
  source/themes/API/index.js
  source/themes/API/loadingspinner.js
  source/themes/simple/SimpleLoadingSpinner.scss
  source/themes/simple/index.js
  source/themes/simple/mixins/loading-spinner.scss
  stories/LoadingSpinner.stories.js
  stories/LoadingSpinner.stories.scss
  stories/images/daedalus-logo.svg
  stories/index.js
  stories/theme-overrides/adaSpinner.scss
  stories/theme-overrides/daedalusSpinner.scss
  stories/theme-overrides/dashedSpinner.scss
  yarn.lock
Labels: feature

#78 [DDW-25] react polymorph striped progress indicator
  CHANGELOG.md
  README.md
  source/components/ProgressBar.js
  source/skins/simple/ProgressBarSkin.js
  source/themes/API/index.js
  source/themes/API/progressbar.js
  source/themes/simple/SimpleProgressBar.scss
  source/themes/simple/index.js
  stories/ProgressBar.stories.js
  stories/ProgressBar.stories.scss
  stories/index.js
  stories/theme-overrides/customProgressBar.scss
Labels: feature

#84 [DDW-197] create header component
  CHANGELOG.md
  source/components/Header.js
  source/skins/simple/HeaderSkin.js
  source/themes/API/header.js
  source/themes/API/index.js
  source/themes/simple/SimpleHeader.scss
  source/themes/simple/index.js
  stories/Header.stories.js
  stories/Header.stories.scss
  stories/index.js
  stories/theme-customizations/Header.custom.scss
  stories/theme-overrides/customHeader.scss
Labels: feature

#85 [DDW-197] create flex layout component
  CHANGELOG.md
  source/components/layout/Base.js
  source/components/layout/Flex.js
  source/components/layout/FlexItem.js
  source/themes/API/flex.js
  source/themes/API/index.js
  source/themes/simple/SimpleFlex.scss
  source/themes/simple/index.js
  source/utils/layout.js
  stories/Layout.stories.js
  stories/Layout.stories.scss
  stories/index.js
  stories/theme-overrides/customFlex.scss
Labels: feature

#86 [DDW-197] create gutter layout component
  CHANGELOG.md
  source/components/layout/Gutter.js
  source/themes/API/gutter.js
  source/themes/API/index.js
  source/themes/simple/SimpleGutter.scss
  source/themes/simple/index.js
  source/utils/props.js
Labels: feature
