Repository input-output-hk/react-polymorph, pull requests merged in 2019-05, with the labels that each got.

#104 Upgrade react-dom to Address Github Vulnerability Warning
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#103 [DDW-604] Add Disabled Text Color CSS Var for Simple Button
  CHANGELOG.md
  source/themes/simple/SimpleButton.scss
  stories/ThemeProvider.stories.js
Labels: chore

#105 [DDW-653] Fix decimal point bug in numeric input
  CHANGELOG.md
  source/components/NumericInput.js
  source/utils/strings.js
Labels: bug

#106 Release/0.8.3
  CHANGELOG.md
  __tests__/__snapshots__/Autocomplete.test.js.snap
  __tests__/__snapshots__/Options.test.js.snap
  __tests__/__snapshots__/Select.test.js.snap
  package.json
  source/components/Autocomplete.js
  source/components/Bubble.js
  source/components/Checkbox.js
  source/components/FormField.js
  source/components/HOC/GlobalListeners.js
  source/components/NumericInput.js
  source/components/Options.js
  source/components/Select.js
  source/skins/simple/AutocompleteSkin.js
  source/skins/simple/BubbleSkin.js
  source/skins/simple/InfiniteScrollSkin.js
  source/skins/simple/InputSkin.js
  source/skins/simple/OptionsSkin.js
  source/skins/simple/SelectSkin.js
  source/skins/simple/TextAreaSkin.js
  source/themes/API/index.js
  source/themes/simple/SimpleButton.scss
  source/themes/simple/SimpleOptions.scss
  source/utils/strings.js
  stories/ThemeProvider.stories.js
  yarn.lock
Labels: release

#107 Chore/ddw 670 setup storybook build on netlify
  .gitignore
  CHANGELOG.md
  package.json
Labels: chore
