Repository input-output-hk/react-polymorph, pull requests merged in 2019-06, with the labels that each got.

#108 Release/0.8.4
  CHANGELOG.md
  __tests__/__snapshots__/Autocomplete.test.js.snap
  __tests__/__snapshots__/Select.test.js.snap
  package.json
  source/components/Autocomplete.js
  source/components/HOC/GlobalListeners.js
  source/components/Options.js
  source/components/Select.js
  source/skins/simple/AutocompleteSkin.js
  source/skins/simple/OptionsSkin.js
  source/skins/simple/SelectSkin.js
Labels: bug, release

#110 Release/0.8.6
  CHANGELOG.md
  source/components/HOC/GlobalListeners.js
Labels: bug, release

#115 [DDW-658] Custom select value and Stepper component
  CHANGELOG.md
  __tests__/Select.test.js
  __tests__/Stepper.test.js
  __tests__/__snapshots__/Select.test.js.snap
  __tests__/__snapshots__/Stepper.test.js.snap
  source/components/Input.js
  source/components/Select.js
  source/components/Stepper.js
  source/components/index.js
  source/skins/simple/InputSkin.js
  source/skins/simple/SelectSkin.js
  source/skins/simple/StepperSkin.js
  source/skins/simple/index.js
  source/themes/API/index.js
  source/themes/API/stepper.js
  source/themes/simple/SimpleInput.scss
  source/themes/simple/SimpleSelect.scss
  source/themes/simple/SimpleStepper.scss
  source/themes/simple/index.js
  stories/Select.stories.js
  stories/Select.stories.scss
  stories/Stepper.stories.js
  stories/index.js
  stories/theme-customizations/Stepper.custom.scss
  stories/theme-overrides/customStepper.scss
Labels: feature

#116 Release/0.8.7
  CHANGELOG.md
  package.json
Labels: release

#117 Updates Contributors in package.json
  CHANGELOG.md
  package.json
Labels: chore
