Repository input-output-hk/react-polymorph, pull requests merged in 2020-01, with the labels that each got.

#125 [DDW-1128] React-polymorph Error is showed after app resizing
  package.json
  source/components/Dropdown.js
  source/components/HOC/GlobalListeners.js
Labels: bug

#127 Release/0.9.1
  CHANGELOG.md
  package.json
Labels: release

#130 Add support for *.module.scss file name convention
  package.json
  scripts/prepare-sass-files-for-publishing.js
  yarn.lock
Labels: feature
