Repository input-output-hk/react-polymorph, pull requests merged in 2021-04, with the labels that each got.

#166 [DDW-602] - Improve PIN entry component UX
  CHANGELOG.md
  source/components/NumericInput.js
  stories/NumericInput.stories.js
Labels: feature

#167 [DDW-588] Refuse inserts over decimal separator
  CHANGELOG.md
  source/components/NumericInput.js
Labels: bug

#165 [DDW-620] Extend React-Polymorph dropdown to include search feature
  .gitignore
  CHANGELOG.md
  package.json
  source/components/Autocomplete.js
  source/components/Bubble.js
  source/components/Dropdown.js
  source/components/HOC/GlobalListeners.js
  source/components/HOC/withTheme.js
  source/components/InfiniteScroll.js
  source/components/Input.js
  source/components/NumericInput.js
  source/components/Options.js
  source/components/Select.js
  source/components/TextArea.js
  source/skins/simple/OptionsSkin.js
  source/skins/simple/SelectSkin.js
  source/themes/API/options.js
  source/themes/simple/SimpleOptions.scss
  source/themes/simple/SimpleSelect.scss
  source/themes/simple/assets/cross.svg
  source/themes/simple/assets/search.svg
  stories/Autocomplete.stories.js
  stories/Select.stories.js
  stories/helpers/dummyData.js
  stories/theme-customizations/Options.custom.scss
  stories/theme-customizations/assets/cross.svg
  stories/theme-customizations/assets/search.svg
  storybook/addons.js
  yarn.lock
Labels: feature

#169 Fixes broken createRef without React.
  source/components/Input.js
Labels: bug

#170 [DDW-646] Fix select search highlight css variable
  CHANGELOG.md
  source/themes/simple/SimpleOptions.scss
Labels: bug

#172 Fix/wrong dependencies
  .yarnrc
  package.json
  yarn.lock
Labels: chore

#175 [DDW-645] Update react-polymorph and implement the search style variables
  .yarnrc
  CHANGELOG.md
  source/skins/simple/OptionsSkin.js
  source/themes/simple/SimpleOptions.scss
Labels: bug

#177 Document new release management
  README.md
  package.json
Labels: chore

#173 [DDW-595] Improve input popover handling
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  __tests__/FormField.test.js
  __tests__/NumericInput.behavior.test.js
  __tests__/__snapshots__/FormField.test.js.snap
  __tests__/__snapshots__/TextArea.test.js.snap
  package.json
  source/components/FormField.js
  source/components/Input.js
  source/skins/simple/FormFieldSkin.js
  source/skins/simple/InputSkin.js
  source/skins/simple/OptionsSkin.js
  source/skins/simple/PasswordInputSkin.js
  source/themes/simple/SimplePasswordInput.scss
  source/utils/hooks.js
  stories/Input.stories.js
Labels: feature, waiting

#179 [DDW-662] Fixes React Polymorph Select search issues
  CHANGELOG.md
  source/components/Options.js
Labels: bug
