Repository input-output-hk/react-polymorph, pull requests merged in 2022-04, with the labels that each got.

#210 [DDW-756] Fix PopOver overlap
  source/themes/simple/SimplePopOver.scss
Labels: bug

#206 [DDW-974] Fix double triggering of checkbox onChange
  .eslintrc
  .gitignore
  CHANGELOG.md
  __tests__/Checkbox.behavior.test.js
  __tests__/__snapshots__/Checkbox.test.js.snap
  package.json
  source/components/Checkbox.js
  source/skins/simple/CheckboxSkin.js
  stories/Checkbox.stories.js
Labels: chore, WIP

#212 Update CHANGELOG.md
  CHANGELOG.md
Labels: release

#213 Update version to 1.0.4
  package.json
Labels: release
